### ISSUE TITLE
[FEATURE] Merge IdkWhoMe's scaffold.

### ISSUE THREAD

**Issue by mems01** [CCBlueX/Old-LiquidBounce-Issues#3913]

**Comment by Teals53** [comment]
yeah and my issues is invalid
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3881

**Comment by ghost** [comment]
Unlike you, I am not asking to add a bunch of modules which probably won't help in anything, I am posting this specific module because I know that with this merged on the official LiquidBounce it would be a lot better + people would like it.

**Comment by EthanSolid** [comment]
Good idea

**Comment by ghost** [comment]
I see this thread being ignored, again, to the people who work on LiquidBounce, if you merge this modified scaffold in the original LiquidBounce, bypasses will be easier to do and users will love it guaranteed. I've already sent you both the specified Custom LiquidBounce to test it out for yourself, Senk Ju/kawaiinekololi. Unless you are already working on that, then excuse me.

**Comment by ghost** [comment]
Remove it, decided not to, as you ignore this thread which is something i don't appreciate.

EDIT: If you are working on it, just tell me, I usually get notified when something is done.

**Comment by Teals53** [comment]
...

**Comment by ghost** [comment]
Alright so it's renamed once again, and I finally got an update from the developers. I realized I had to send them the source code, so yeah, sent to both of them.
